name: pihole

services:
  pihole:
    image: jacklul/pihole:latest # https://github.com/jacklul/pihole-updatelists https://github.com/pi-hole/docker-pi-hole
    container_name: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - PIHOLE_UID=${PUID}
      - PIHOLE_GID=${PGID}
      - FTLCONF_dns_dnssec=true
      - FTLCONF_dns_upstreams=${FTLCONF_dns_upstreams}
      - FTLCONF_webserver_api_password=${FTLCONF_webserver_api_password}
      - FTLCONF_dns_listeningMode=ALL
      - CRONTAB_STRING="25 2 * * 6"
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-pihole-updatelists/:/etc/pihole-updatelists/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
